name: Build iOS IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app

    - name: Build and Archive
      run: |
        xcodebuild -project "fever_free-IOS.xcodeproj" -scheme "fever_free-IOS" -sdk iphoneos -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO SYMROOT=$(pwd)/build
        
        mkdir Payload
        cp -R build/Release-iphoneos/*.app Payload/
        zip -r fever_free-IOS.ipa Payload

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fever_free-IOS-ipa
        path: fever_free-IOS.ipa
